# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8663eb04a2f2e8f44697e4dbcf4c67471f5ce017b74a29d15fabdec7c0f7ccea45c82ffbde22b7d8700bb8110dff8d333f57c9f01d887f5b891fedbea869f809

test:
  secret_key_base: 84328836d17bb7de0bca5f19d4165ddc6c8abbdf0049e7018aa73d373c1ef052b7af3803917494bdd9d0b5fdbe71f0082e79a07b51b49fe03cdb87fb605d631e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
